// <auto-generated />
using System.Runtime.InteropServices;

namespace SharpSDL.Interop
{
    internal static unsafe partial class SDL2
    {
        [LibraryImport("SDL2", EntryPoint = "SDL_OpenURL")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial int OpenURL([NativeTypeName("const char *")] byte* url);
    }
}
